[project]
name = "custom-component"
version = "0.1.0"
description = "Test component"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "custom-component-module",
    "pulumi",
    "pulumi-aws",
    "pydantic>=2.11.9",
]

[tool.uv.sources]
custom-component-module = { path = "../custom_component_module" }
