# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .ec2_security_group import *
from .provider import *
from .vpc import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "custom-resource-provider",
  "mod": "index",
  "fqn": "pulumi_custom_resource_provider",
  "classes": {
   "custom-resource-provider:index:EC2SecurityGroup": "EC2SecurityGroup",
   "custom-resource-provider:index:VPC": "VPC"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "custom-resource-provider",
  "token": "pulumi:providers:custom-resource-provider",
  "fqn": "pulumi_custom_resource_provider",
  "class": "Provider"
 }
]
"""
)
