# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'EC2SecurityGroupRuleProtocol',
]


@pulumi.type_token("custom-resource-provider:index:EC2SecurityGroupRuleProtocol")
class EC2SecurityGroupRuleProtocol(_builtins.str, Enum):
    """
    Enum for supported protocols in security group rules.
    """
    TCP = "tcp"
    UDP = "udp"
    ICMP = "icmp"
    ALL = "all"
    ANY = "-1"
