# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'EC2SecurityGroupEgressRuleArgs',
    'EC2SecurityGroupEgressRuleArgsDict',
    'EC2SecurityGroupIngressRuleArgs',
    'EC2SecurityGroupIngressRuleArgsDict',
]

MYPY = False

if not MYPY:
    class EC2SecurityGroupEgressRuleArgsDict(TypedDict):
        """
        Config for an AWS My Security Group ingress rule.
        """
        description: _builtins.str
        """
        The description of the rule.
        """
        name: _builtins.str
        """
        The name of the rule. Must be in kebab-case format.
        """
        protocol: 'EC2SecurityGroupRuleProtocol'
        """
        The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        """
        destination_security_group_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        The destination security group ID this rule applies to.
        """
        from_port: NotRequired[_builtins.int]
        """
        The start port of the range for the rule.
        """
        ipv4_cidr_block: NotRequired[pulumi.Input[_builtins.str]]
        """
        The IPv4 CIDR block this rule applies to.
        """
        ipv6_cidr_block: NotRequired[pulumi.Input[_builtins.str]]
        """
        The IPv6 CIDR block this rule applies to.
        """
        prefix_list_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        The prefix list ID this rule applies to.
        """
        tags: NotRequired[Mapping[str, pulumi.Input[_builtins.str]]]
        """
        The tags for the rule.
        """
        to_port: NotRequired[_builtins.int]
        """
        The end port of the range for the rule.
        """
elif False:
    EC2SecurityGroupEgressRuleArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class EC2SecurityGroupEgressRuleArgs:
    def __init__(__self__, *,
                 description: _builtins.str,
                 name: _builtins.str,
                 protocol: 'EC2SecurityGroupRuleProtocol',
                 destination_security_group_id: Optional[pulumi.Input[_builtins.str]] = None,
                 from_port: Optional[_builtins.int] = None,
                 ipv4_cidr_block: Optional[pulumi.Input[_builtins.str]] = None,
                 ipv6_cidr_block: Optional[pulumi.Input[_builtins.str]] = None,
                 prefix_list_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[Mapping[str, pulumi.Input[_builtins.str]]] = None,
                 to_port: Optional[_builtins.int] = None):
        """
        Config for an AWS My Security Group ingress rule.
        :param _builtins.str description: The description of the rule.
        :param _builtins.str name: The name of the rule. Must be in kebab-case format.
        :param 'EC2SecurityGroupRuleProtocol' protocol: The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        :param pulumi.Input[_builtins.str] destination_security_group_id: The destination security group ID this rule applies to.
        :param _builtins.int from_port: The start port of the range for the rule.
        :param pulumi.Input[_builtins.str] ipv4_cidr_block: The IPv4 CIDR block this rule applies to.
        :param pulumi.Input[_builtins.str] ipv6_cidr_block: The IPv6 CIDR block this rule applies to.
        :param pulumi.Input[_builtins.str] prefix_list_id: The prefix list ID this rule applies to.
        :param Mapping[str, pulumi.Input[_builtins.str]] tags: The tags for the rule.
        :param _builtins.int to_port: The end port of the range for the rule.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "protocol", protocol)
        if destination_security_group_id is not None:
            pulumi.set(__self__, "destination_security_group_id", destination_security_group_id)
        if from_port is not None:
            pulumi.set(__self__, "from_port", from_port)
        if ipv4_cidr_block is not None:
            pulumi.set(__self__, "ipv4_cidr_block", ipv4_cidr_block)
        if ipv6_cidr_block is not None:
            pulumi.set(__self__, "ipv6_cidr_block", ipv6_cidr_block)
        if prefix_list_id is not None:
            pulumi.set(__self__, "prefix_list_id", prefix_list_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if to_port is not None:
            pulumi.set(__self__, "to_port", to_port)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the rule.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: _builtins.str):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the rule. Must be in kebab-case format.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> 'EC2SecurityGroupRuleProtocol':
        """
        The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: 'EC2SecurityGroupRuleProtocol'):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="destinationSecurityGroupId")
    def destination_security_group_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The destination security group ID this rule applies to.
        """
        return pulumi.get(self, "destination_security_group_id")

    @destination_security_group_id.setter
    def destination_security_group_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "destination_security_group_id", value)

    @_builtins.property
    @pulumi.getter(name="fromPort")
    def from_port(self) -> Optional[_builtins.int]:
        """
        The start port of the range for the rule.
        """
        return pulumi.get(self, "from_port")

    @from_port.setter
    def from_port(self, value: Optional[_builtins.int]):
        pulumi.set(self, "from_port", value)

    @_builtins.property
    @pulumi.getter(name="ipv4CidrBlock")
    def ipv4_cidr_block(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The IPv4 CIDR block this rule applies to.
        """
        return pulumi.get(self, "ipv4_cidr_block")

    @ipv4_cidr_block.setter
    def ipv4_cidr_block(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv4_cidr_block", value)

    @_builtins.property
    @pulumi.getter(name="ipv6CidrBlock")
    def ipv6_cidr_block(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The IPv6 CIDR block this rule applies to.
        """
        return pulumi.get(self, "ipv6_cidr_block")

    @ipv6_cidr_block.setter
    def ipv6_cidr_block(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv6_cidr_block", value)

    @_builtins.property
    @pulumi.getter(name="prefixListId")
    def prefix_list_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The prefix list ID this rule applies to.
        """
        return pulumi.get(self, "prefix_list_id")

    @prefix_list_id.setter
    def prefix_list_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix_list_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, pulumi.Input[_builtins.str]]]:
        """
        The tags for the rule.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[Mapping[str, pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="toPort")
    def to_port(self) -> Optional[_builtins.int]:
        """
        The end port of the range for the rule.
        """
        return pulumi.get(self, "to_port")

    @to_port.setter
    def to_port(self, value: Optional[_builtins.int]):
        pulumi.set(self, "to_port", value)


if not MYPY:
    class EC2SecurityGroupIngressRuleArgsDict(TypedDict):
        """
        Config for an AWS My Security Group ingress rule.
        """
        description: _builtins.str
        """
        The description of the rule.
        """
        name: _builtins.str
        """
        The name of the rule. Must be in kebab-case format.
        """
        protocol: 'EC2SecurityGroupRuleProtocol'
        """
        The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        """
        from_port: NotRequired[_builtins.int]
        """
        The start port of the range for the rule.
        """
        ipv4_cidr_block: NotRequired[pulumi.Input[_builtins.str]]
        """
        The IPv4 CIDR block this rule applies to.
        """
        ipv6_cidr_block: NotRequired[pulumi.Input[_builtins.str]]
        """
        The IPv6 CIDR block this rule applies to.
        """
        prefix_list_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        The prefix list ID this rule applies to.
        """
        source_security_group_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        The source security group ID this rule applies to.
        """
        tags: NotRequired[Mapping[str, pulumi.Input[_builtins.str]]]
        """
        The tags for the rule.
        """
        to_port: NotRequired[_builtins.int]
        """
        The end port of the range for the rule.
        """
elif False:
    EC2SecurityGroupIngressRuleArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class EC2SecurityGroupIngressRuleArgs:
    def __init__(__self__, *,
                 description: _builtins.str,
                 name: _builtins.str,
                 protocol: 'EC2SecurityGroupRuleProtocol',
                 from_port: Optional[_builtins.int] = None,
                 ipv4_cidr_block: Optional[pulumi.Input[_builtins.str]] = None,
                 ipv6_cidr_block: Optional[pulumi.Input[_builtins.str]] = None,
                 prefix_list_id: Optional[pulumi.Input[_builtins.str]] = None,
                 source_security_group_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[Mapping[str, pulumi.Input[_builtins.str]]] = None,
                 to_port: Optional[_builtins.int] = None):
        """
        Config for an AWS My Security Group ingress rule.
        :param _builtins.str description: The description of the rule.
        :param _builtins.str name: The name of the rule. Must be in kebab-case format.
        :param 'EC2SecurityGroupRuleProtocol' protocol: The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        :param _builtins.int from_port: The start port of the range for the rule.
        :param pulumi.Input[_builtins.str] ipv4_cidr_block: The IPv4 CIDR block this rule applies to.
        :param pulumi.Input[_builtins.str] ipv6_cidr_block: The IPv6 CIDR block this rule applies to.
        :param pulumi.Input[_builtins.str] prefix_list_id: The prefix list ID this rule applies to.
        :param pulumi.Input[_builtins.str] source_security_group_id: The source security group ID this rule applies to.
        :param Mapping[str, pulumi.Input[_builtins.str]] tags: The tags for the rule.
        :param _builtins.int to_port: The end port of the range for the rule.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "protocol", protocol)
        if from_port is not None:
            pulumi.set(__self__, "from_port", from_port)
        if ipv4_cidr_block is not None:
            pulumi.set(__self__, "ipv4_cidr_block", ipv4_cidr_block)
        if ipv6_cidr_block is not None:
            pulumi.set(__self__, "ipv6_cidr_block", ipv6_cidr_block)
        if prefix_list_id is not None:
            pulumi.set(__self__, "prefix_list_id", prefix_list_id)
        if source_security_group_id is not None:
            pulumi.set(__self__, "source_security_group_id", source_security_group_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if to_port is not None:
            pulumi.set(__self__, "to_port", to_port)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the rule.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: _builtins.str):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the rule. Must be in kebab-case format.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> 'EC2SecurityGroupRuleProtocol':
        """
        The protocol for the rule. Can be 'tcp', 'udp', 'icmp', 'all', or '-1'.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: 'EC2SecurityGroupRuleProtocol'):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="fromPort")
    def from_port(self) -> Optional[_builtins.int]:
        """
        The start port of the range for the rule.
        """
        return pulumi.get(self, "from_port")

    @from_port.setter
    def from_port(self, value: Optional[_builtins.int]):
        pulumi.set(self, "from_port", value)

    @_builtins.property
    @pulumi.getter(name="ipv4CidrBlock")
    def ipv4_cidr_block(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The IPv4 CIDR block this rule applies to.
        """
        return pulumi.get(self, "ipv4_cidr_block")

    @ipv4_cidr_block.setter
    def ipv4_cidr_block(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv4_cidr_block", value)

    @_builtins.property
    @pulumi.getter(name="ipv6CidrBlock")
    def ipv6_cidr_block(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The IPv6 CIDR block this rule applies to.
        """
        return pulumi.get(self, "ipv6_cidr_block")

    @ipv6_cidr_block.setter
    def ipv6_cidr_block(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ipv6_cidr_block", value)

    @_builtins.property
    @pulumi.getter(name="prefixListId")
    def prefix_list_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The prefix list ID this rule applies to.
        """
        return pulumi.get(self, "prefix_list_id")

    @prefix_list_id.setter
    def prefix_list_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix_list_id", value)

    @_builtins.property
    @pulumi.getter(name="sourceSecurityGroupId")
    def source_security_group_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The source security group ID this rule applies to.
        """
        return pulumi.get(self, "source_security_group_id")

    @source_security_group_id.setter
    def source_security_group_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "source_security_group_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, pulumi.Input[_builtins.str]]]:
        """
        The tags for the rule.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[Mapping[str, pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="toPort")
    def to_port(self) -> Optional[_builtins.int]:
        """
        The end port of the range for the rule.
        """
        return pulumi.get(self, "to_port")

    @to_port.setter
    def to_port(self, value: Optional[_builtins.int]):
        pulumi.set(self, "to_port", value)


