# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *
from ._inputs import *

__all__ = ['EC2SecurityGroupArgs', 'EC2SecurityGroup']

@pulumi.input_type
class EC2SecurityGroupArgs:
    def __init__(__self__, *,
                 description: _builtins.str,
                 name: _builtins.str,
                 egress_rules: Optional[Mapping[str, 'EC2SecurityGroupEgressRuleArgs']] = None,
                 ingress_rules: Optional[Mapping[str, 'EC2SecurityGroupIngressRuleArgs']] = None,
                 tags: Optional[Mapping[str, pulumi.Input[_builtins.str]]] = None,
                 vpc_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a EC2SecurityGroup resource.
        :param _builtins.str description: The description of the security group.
        :param _builtins.str name: The name of the security group. Must be in kebab-case format.
        :param Mapping[str, 'EC2SecurityGroupEgressRuleArgs'] egress_rules: The egress rules for the security group. The keys will be used in the Pulumi resource IDs and must be
                   in kebab-case format.
        :param Mapping[str, 'EC2SecurityGroupIngressRuleArgs'] ingress_rules: The ingress rules for the security group. The keys will be used in the Pulumi resource IDs and
                   must be in kebab-case format.
        :param Mapping[str, pulumi.Input[_builtins.str]] tags: The tags to apply to the security group resource.
        :param pulumi.Input[_builtins.str] vpc_id: The VPC ID to create the security group in.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "name", name)
        if egress_rules is not None:
            pulumi.set(__self__, "egress_rules", egress_rules)
        if ingress_rules is not None:
            pulumi.set(__self__, "ingress_rules", ingress_rules)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if vpc_id is not None:
            pulumi.set(__self__, "vpc_id", vpc_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the security group.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: _builtins.str):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the security group. Must be in kebab-case format.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="egressRules")
    def egress_rules(self) -> Optional[Mapping[str, 'EC2SecurityGroupEgressRuleArgs']]:
        """
        The egress rules for the security group. The keys will be used in the Pulumi resource IDs and must be
            in kebab-case format.
        """
        return pulumi.get(self, "egress_rules")

    @egress_rules.setter
    def egress_rules(self, value: Optional[Mapping[str, 'EC2SecurityGroupEgressRuleArgs']]):
        pulumi.set(self, "egress_rules", value)

    @_builtins.property
    @pulumi.getter(name="ingressRules")
    def ingress_rules(self) -> Optional[Mapping[str, 'EC2SecurityGroupIngressRuleArgs']]:
        """
        The ingress rules for the security group. The keys will be used in the Pulumi resource IDs and
            must be in kebab-case format.
        """
        return pulumi.get(self, "ingress_rules")

    @ingress_rules.setter
    def ingress_rules(self, value: Optional[Mapping[str, 'EC2SecurityGroupIngressRuleArgs']]):
        pulumi.set(self, "ingress_rules", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, pulumi.Input[_builtins.str]]]:
        """
        The tags to apply to the security group resource.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[Mapping[str, pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The VPC ID to create the security group in.
        """
        return pulumi.get(self, "vpc_id")

    @vpc_id.setter
    def vpc_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpc_id", value)


@pulumi.type_token("custom-resource-provider:index:EC2SecurityGroup")
class EC2SecurityGroup(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[_builtins.str] = None,
                 egress_rules: Optional[Mapping[str, Union['EC2SecurityGroupEgressRuleArgs', 'EC2SecurityGroupEgressRuleArgsDict']]] = None,
                 ingress_rules: Optional[Mapping[str, Union['EC2SecurityGroupIngressRuleArgs', 'EC2SecurityGroupIngressRuleArgsDict']]] = None,
                 name: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, pulumi.Input[_builtins.str]]] = None,
                 vpc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        AWS My Security Group.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param _builtins.str description: The description of the security group.
        :param Mapping[str, Union['EC2SecurityGroupEgressRuleArgs', 'EC2SecurityGroupEgressRuleArgsDict']] egress_rules: The egress rules for the security group. The keys will be used in the Pulumi resource IDs and must be
                   in kebab-case format.
        :param Mapping[str, Union['EC2SecurityGroupIngressRuleArgs', 'EC2SecurityGroupIngressRuleArgsDict']] ingress_rules: The ingress rules for the security group. The keys will be used in the Pulumi resource IDs and
                   must be in kebab-case format.
        :param _builtins.str name: The name of the security group. Must be in kebab-case format.
        :param Mapping[str, pulumi.Input[_builtins.str]] tags: The tags to apply to the security group resource.
        :param pulumi.Input[_builtins.str] vpc_id: The VPC ID to create the security group in.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EC2SecurityGroupArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        AWS My Security Group.

        :param str resource_name: The name of the resource.
        :param EC2SecurityGroupArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EC2SecurityGroupArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[_builtins.str] = None,
                 egress_rules: Optional[Mapping[str, Union['EC2SecurityGroupEgressRuleArgs', 'EC2SecurityGroupEgressRuleArgsDict']]] = None,
                 ingress_rules: Optional[Mapping[str, Union['EC2SecurityGroupIngressRuleArgs', 'EC2SecurityGroupIngressRuleArgsDict']]] = None,
                 name: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, pulumi.Input[_builtins.str]]] = None,
                 vpc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EC2SecurityGroupArgs.__new__(EC2SecurityGroupArgs)

            if description is None and not opts.urn:
                raise TypeError("Missing required property 'description'")
            __props__.__dict__["description"] = description
            __props__.__dict__["egress_rules"] = egress_rules
            __props__.__dict__["ingress_rules"] = ingress_rules
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["tags"] = tags
            __props__.__dict__["vpc_id"] = vpc_id
            __props__.__dict__["security_group_id"] = None
        super(EC2SecurityGroup, __self__).__init__(
            'custom-resource-provider:index:EC2SecurityGroup',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the security group.
        """
        return pulumi.get(self, "security_group_id")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> pulumi.Output[_builtins.str]:
        """
        The VPC ID the security group is in.
        """
        return pulumi.get(self, "vpc_id")

